[window]
padding = { x = 5, y = 5 }
dynamic_padding = true

[font]
size = 12
normal = { family = "UbuntuMono Nerd Font Propo", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font Propo", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font Propo", style = "Italic" }

# gruvbox theme:
[colors]

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[colors.normal]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x3c3836"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"
