import = [
  "~/.config/alacritty/themes/tokyo-night.toml", 
]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.95

[font]
size = 12
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }

[cursor]
style = { shape = "Underline", blinking = "Off" }
